spring:
  application:
    name: mydemo
  datasource:
    hikari:
      #      jdbc-url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8
      jdbc-url: jdbc:mysql://172.30.1.94:3306/batch?useUnicode=true&characterEncoding=utf8
      username: batch
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
      enabled: false
